### ISSUE TITLE
Prevents program from exiting

### ISSUE THREAD

**Issue by eshao** [kenperkins/winston-papertrail#14]
Noticed a peculiar issue in that any library that I included winston-papertrail in would never actually exit. Here is how to reproduce:

Put the following in test.js:

``` js
  var winston = require('winston');

  //
  // Requiring `winston-papertrail` will expose
  // `winston.transports.Papertrail`
  //
  require('winston-papertrail').Papertrail;

  var logger = new winston.Logger({
    transports: [
        new winston.transports.Papertrail({
            host: 'logs.papertrailapp.com',
            port: 12345
        })
    ]
  });

  logger.info('this is my message2');
```

Execute it with `node test.js` and the program will never exit. It will correctly log your message to Papertrail. 

This behavior doesn't exist with, say, just the default Console logger.

This bug is reproduceable on 0.1.1 and 0.1.2, using winston 0.6.2. Also reproducable using 0.1.2 and the latest winston 0.7.1. I'm using node 0.8.14.

**Comment by river-jade** [comment]
This works for me, but I get an ugly 'socket hang up' exception in the console. Any suggestions on how to resolve this?

Thanks for the library by the way, very handy :).
