### ISSUE TITLE
Error events for ECONNREFUSED

### ISSUE THREAD

**Issue by scottcorgan** [kenperkins/winston-papertrail#20]
Recently ran into a case were the connection refused because of a log limit being reached. Are there errors emitted by the module that would allow me to catch that error?

**Comment by chaserelock** [comment]
This happened to me as well and temporarily brought down a production box - would love to see this caught/catchable

**Comment by troy** [comment]
Hey all, if you pull `master`, the final fix for this (#61) should now be in the code and will be released to NPM in the next week or two. Even without an error handler defined, connection errors now default to being output to the console but not affecting runtime.

If you pull `master` (or use an eventual `1.0.4` release, when it's out) and see any impact from connection errors, please open a new issue with the transcript and version in use.
