### ISSUE TITLE
Custom winston log levels submit 'false' to papertrail.

### ISSUE THREAD

**Issue by joshmackey** [kenperkins/winston-papertrail#33]
If a custom log level isn't an available Severity in glossy, the single word 'false' gets sent to papertrail.

**Comment by kenperkins** [comment]
Do you have a repro?

**Comment by joshmackey** [comment]
False gets outputted even if you use the built in log levels.

I can repro with the following: (Private details replaced with ****)

````
'use strict';

var winstonBase = require('winston'),
    Papertrail = require('winston-papertrail').Papertrail;

var winston = new (winstonBase.Logger)({
  transports: [
    new (winstonBase.transports.Console)({
      colorize: true,
      level: 'silly'
    })
  ]
});

winston.add(Papertrail, {
  host: '****',
  port: '****',
  level: 'silly',
});


winston.info('info test');
winston.silly('silly test');
````

The console outputs:
````
info: info test
silly: silly test
````

Papertrail outputs:
````
Feb 09 15:32:28 **** default: info info test
Feb 09 15:32:28 **** default: false 
````

**Comment by joshmackey** [comment]
Happens at line 342 in winston-papertrail.js.

````self.producer.produce```` returns false.

````
        msg += self.producer.produce({
            severity: level,
            host: hostname,
            appName: program,
            date: new Date(),
            message: self.logFormat(self.colorize ? winston.config.colorize(level) : level, gap + lines[i])
        }) + '\r\n';
````

**Comment by paps** [comment]
Yep I've got the same issue. And it was tricky to discover because I kept receiving "info" messages, but not my custom severity messages...

Is someone working on this, or do you want me to look at it?

**Comment by kenperkins** [comment]
I'm certainly very open to a PR, I haven't gotten to this yet.

**Comment by paps** [comment]
Well I've looked at it and it seems Glossy only accepts these severities
```
var SeverityIndex = {
'emerg': 0, // Emergency: system is unusable
'emergency': 0,
'alert': 1, // Alert: action must be taken immediately
'crit': 2, // Critical: critical conditions
'critical': 2,
'err': 3, // Error: error conditions
'error': 3,
'warn': 4, // Warning: warning conditions
'warning': 4,
'notice': 5, // Notice: normal but significant condition
'info': 6 , // Informational: informational messages
'information': 6,
'informational': 6,
'debug': 7 // Debug: debug-level messages
};
```
because it aims at being compliant with syslog RFCs.

I haven't got a lot of time on my hands so I'm just going to change my code and use these severity levels.

**Comment by MeanwhileMedia** [comment]
Is this fix going to be merged? I am currently unable to view exceptions/errors in papertrail.

**Comment by darkbasic** [comment]
Same problem on papertrailapp.com, any fix?

**Comment by derekstavis** [comment]
This is not solved yet. I still see this issue when using `winston-papertrail` from npm.

**Comment by matteocontrini** [comment]
@derekstavis this commit hasn't been published as a release on npm, yet

**Comment by derekstavis** [comment]
Ah, just saw this @matteocontrini, thanks!

Installing from Github seems to solve the issue!

**Comment by jdpnielsen** [comment]
Would it be possible to get a heads up when this is pushed to npm? 
I would very much like to replace the installation from Github, when that happens.

**Comment by troy** [comment]
This is live on NPM in version `1.0.3`.
