### ISSUE TITLE
API Token, X-Papertrail-Token header

### ISSUE THREAD

**Issue by liviuignat** [kenperkins/winston-papertrail#35]
I don't see any implementation that accepts X-Papertrail-Token header to pass the token.

Cheers,
Liviu

**Comment by troy** [comment]
The X-Papertrail-Token header is used for API access, as for https://github.com/papertrail/papertrail-cli. It's not used for log submission, though. Head over to https://papertrailapp.com/dashboard and click "Add Systems" (upper right corner) to see your settings for sending logs.

**Comment by kenperkins** [comment]
Absent @troy's feedback, was there a specific reason you believe we need to be doing API access as well?

**Comment by liviuignat** [comment]
Hi,

I was investigating it as a Heroku add-on and from the interface they provide with papertrail, port and hostname are nowhere to be found, so I initially thought they dropped the hostname and port connection. I just created a new account via their site and it works.

Thanks for the prompt answers,
Cheers,

**Comment by troy** [comment]
If you're using Heroku, you can provision the Papertrail add-on and send logs to stdout ([like this](https://devcenter.heroku.com/articles/logging#writing-to-your-log)). No need to use `winston-papertrail` at all, nor care about the destination. If you're using winston, the `Console` transport is probably the best fit.

[Here's](http://help.papertrailapp.com/kb/hosting-services/heroku/) the tradeoffs of different ways to log to Papertrail from Heroku apps.
