### ISSUE TITLE
winston.handleExceptions submits 'false' to papertrail. 

### ISSUE THREAD

**Issue by chirillc** [kenperkins/winston-papertrail#40]
Hi,
I'm trying to use winston-papertrail to log nodejs/express unhandled exceptions but they show up as "false" in papertrail.
Code snippet:
```
var winston = require('winston');
winston.handleExceptions(
  new winston.transports.Papertrail({
        host: 'xxx',
        port: xxx,
        hostname: 'xxx',
        inlineMeta: true
    })            
);
```

Then I throw an exception without catching it, like this:
```
throw Error('boo');
```
After spending some time looking into it I could find out that it looks like "level" is being passed as undefined into: 
```
Papertrail.prototype.sendMessage = function (hostname, program, level, message) {
```

**Comment by bitomule** [comment]
I have this issue too, did you find how to fix it?

**Comment by MeanwhileMedia** [comment]
I have the same issue.

**Comment by alexanderperls** [comment]
I have the same issue. Is there a workaround?

**Comment by brocksamson** [comment]
There is a way to work around this, here is my winston-papertrail handleExceptions code block.

    var paperTrailLogger = new winston.transports.Papertrail(papertrailConfig);
    paperTrailLogger.exceptionsLevel = 'error';
    winston.handleExceptions(paperTrailLogger)

The Papertrail constructor function doesn't set exceptionsLevel so the default transport exception handling function ends up sending undefined down to Papertrail.log function.

**Comment by whythecode** [comment]
would also be solved by #34

**Comment by whythecode** [comment]
+1 though, @brocksamson solves my problem without having to fork the repo:)

```
var log       = new winston.Logger()
  , transport = new transportClass( transportConfig.config )

transport.exceptionsLevel = 'error'
log.handleExceptions( transport )

// undefined -> no config needed, true -> is already initialized
log.add( transport, undefined, true )
```

**Comment by brocksamson** [comment]
Note that a complete exception handling solution also requires the code changes from #44.  The code above will handle uncaught exceptions because the base transport class from winston creates the serialized representation of the object.  This will not work however:

    try{
        throw new Exception("Guns are for sissies.");
    }
    catch(ex){
        log.error(ex);
    }

See #42 for an explanation of why this occurs.

**Comment by matteocontrini** [comment]
@brocksamson pull request #44 is pending for that issue

**Comment by whythecode** [comment]
@brocksamson - ugh, you're right. I'm actually not even getting the "false" messages now. Hopefully this will be fixed soon..........

**Comment by jareware** [comment]
Also seeing this, any chance of updating this transport?

**Comment by troy** [comment]
@jareware (and anyone else who wants this): check out and subscribe to #34

**Comment by jareware** [comment]
Good to know, thanks!

**Comment by troy** [comment]
If you're reading this message, we'd love if you can pull the current master of winston-papertrail and run it. We'll wait at least 2 weeks to see whether any issues come up from wider use of this and one other change. If you encounter problems with master which don't occur in the current release, please open a new GitHub Issue with the transcript and reference #34.

**Comment by troy** [comment]
This is live on NPM in version `1.0.3`.
