### ISSUE TITLE
Pass meta data into logFormat()

### ISSUE THREAD

**Issue by ricolo** [kenperkins/winston-papertrail#41]
Currently, `logFormat()` input arguments are `level` and `message`, and I wonder if meta data can also be passed into the function for reformatting.

I use meta data to identify the log from different components of my system, so it may not be the best way to display if it is only printed at the end of the log message for meta data. Winston's file and console transport also provide meta data for the log formatter.

**Comment by cymen** [comment]
I expected it to work this way too so I could log a single line if I wanted to instead of a bunch of lines. My use case is logging requests and I just want to emit a typical Apache-style entry to papertrail. Is there support for this if a PR is done or is it best to fork and make a new module?

**Comment by cymen** [comment]
@ricolo I opened a PR that adds this: https://github.com/kenperkins/winston-papertrail/pull/50

If that gets merged, you can do:

```js
logFormat: function(level, message, originalMessage, meta) {
  return 'META ' + meta;
}
```

Note that winston-paptertrail formats the message and I opened the PR as I want the original message so I can format it. So that 3rd parameter (originalMessage) may not be interesting to you but would be present.

**Comment by cymen** [comment]
@ricolo The fix is now in PR #51. It turned out I needed meta too not another part so I added a new option that is `messageFormat` (#51 has an example).

**Comment by ricolo** [comment]
Thanks a lot @cymen, would you also modify the documentation (e.g. https://github.com/kenperkins/winston-papertrail#advanced-usage) as well to reflect the expanded capability?

**Comment by cymen** [comment]
@ricolo I did in PR #51 but it hasn't been merged yet. I needed this ASAP so I temporarily put a fork of this out here:

https://www.npmjs.com/package/winston-papertrail-enhanced

You could try that to get the functionality. But hopefully #51 will get in soon and I'll deprecate my fork.

**Comment by ricolo** [comment]
@cymen I overlooked it, thanks!

**Comment by matteocontrini** [comment]
This issue should stay open as long as the PR is open.
