### ISSUE TITLE
Cannot flush logs before process ends

### ISSUE THREAD

**Issue by JADurham909** [kenperkins/winston-papertrail#52]
I have noticed that when a process ends, not all the logs are written because they are still in the buffer.  File transport has a flush event you can hook on to prevent this.  This transport does not offer the same,  so I have had to do something like this...

```
//allow papertrail to flush the buffer
setTimeout(() => {
    logger.info('lambda#handler: success');
    context.succeed('success');
}, 1000);
```

**Comment by jortizsao** [comment]
Yes, I have the same issue. Would be great if you can hook this flush event
