### ISSUE TITLE
PT Account and Authorization?

### ISSUE THREAD

**Issue by timscott** [kenperkins/winston-papertrail#60]
The README seems to be missing specifics on how to send to a particular Papertrail account or how to authorize.

**Comment by matteocontrini** [comment]
Host and port are enough, what authorization are you referring to?

**Comment by timscott** [comment]
Sorry, wrong word. I mean authentication. Is there some means to authenticate, or can anyone send logs into my account?

**Comment by troy** [comment]
@timscott Hit [Destinations](https://papertrailapp.com/account/destinations), then the Settings button, then choose the "Accept logs from unrecognized systems?" behavior which fits your topology.

**Comment by timscott** [comment]
Interesting, obviously I was not aware of PT's novel approach to trust. So if I leave "Allow new systems?" set to true, anyone who can guess my subdomain and port (which is not obscure at all) would be free to spam my logs with porn links or something?

Sorry, I know this is not Papertrail support. Thanks for any info, and feel free to close the ticket.

**Comment by matteocontrini** [comment]
Anyone can send logs to your account if they know the host, the port and the "system" names that you have decided to add in your account.

Anyway, @troy works at Papertrail :)
