### ISSUE TITLE
Connection error 

### ISSUE THREAD

**Issue by balibart** [kenperkins/winston-papertrail#73]
I'm having a connection problem while trying to implement the basic winston-papertrail config. 
Here is my trace : 
Papertrail connection error:  TypeError: net.createConnection is not a function
    at connectStream (winston-papertrail.js:211)
    at new ./node_modules/winston-papertrail/lib/winston-papertrail.js.exports.Papertrail (winston-papertrail.js:158)

Seems like a missing dependency maybe?
npm install net didn't solve it

**Comment by Edulopez** [comment]
Why this was closed? @balibart  The issue is still happening.

**Comment by snair-user** [comment]
I also facing this issue, please give solution
